export const MY_TRAVEL = [
    { icon: '⛰️', name: '산' },
    { icon: '🌊', name: '바다' },
    { icon: '🏙️', name: '도시' },
    { icon: '🌿', name: '자연' },
    { icon: '📝', name: '계획' },
    { icon: '🕊️', name: '자유' },
    { icon: '🙋‍♀️', name: '혼자' },
    { icon: '🤝', name: '함께' },
    { icon: '🇰🇷', name: '국내' },
    { icon: '✈️', name: '해외' },
    { icon: '🌟', name: '유명' },
    { icon: '🏘️', name: '로컬' },
    { icon: '🎭', name: '문화' },
    { icon: '👟', name: '도보' },
    { icon: '🚗', name: '차량' },
    { icon: '🏝️', name: '휴식' },
    { icon: '🗺️', name: '모험' },
    { icon: '💨', name: '짧게' },
    { icon: '🧳', name: '길게' },
];
